# Generated by Django 4.1 on 2022-08-04 11:32

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0002_alter_candidate_category_alter_vacancy_category'),
    ]

    operations = [
        migrations.CreateModel(
            name='Statistics',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('name', models.CharField(max_length=100)),
            ],
            options={
                'abstract': False,
            },
        ),
        migrations.AlterField(
            model_name='vacancy',
            name='company',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='vacancies', to='vacancy.company'),
        ),
        migrations.AddField(
            model_name='candidate',
            name='statistics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='candidates', to='vacancy.statistics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='company',
            name='statistics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, related_name='companies', to='vacancy.statistics'),
            preserve_default=False,
        ),
        migrations.AddField(
            model_name='vacancy',
            name='statistics',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='vacancy.statistics'),
            preserve_default=False,
        ),
    ]
