# Generated by Django 4.1 on 2022-08-04 11:34

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('vacancy', '0003_statistics_alter_vacancy_company_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='candidate',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='company',
            name='statistics',
        ),
        migrations.RemoveField(
            model_name='vacancy',
            name='statistics',
        ),
        migrations.DeleteModel(
            name='Statistics',
        ),
    ]
